name: Run Shell Commands

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Run shell commands
        id: job_1
        run: |
          GIT_HASH=$(git ls-remote https://github.com/WebOfTrust/keripy HEAD)
          echo HASH=${GIT_HASH:0:7} >> $GITHUB_ENV
          echo HASH_2=${GIT_HASH:0:7} >> $GITHUB_OUTPUT
        # echo $HASH
        # echo "$HASH"

      - name: Show results
        run: |
          echo $HASH
          echo "${{ env.HASH }}"
          echo "${{ steps.job_1.outputs.HASH_2 }}"


  job_2:
    runs-on: ubuntu-latest
    needs: [job_1]

    steps:
      - name: Show results 1
        run: |
          echo "${{ env.HASH }}"
          echo $HASH


      - name: Show results 2
        run: |
          echo "${{ steps.job_1.outputs.HASH_2 }}"
          echo "${{ steps.git_hash_collector.outputs.HASH_2 }}"
          echo $HASH_2