name: Run Shell Commands

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Run shell commands
        run: |
          HASH=$(git ls-remote https://github.com/WebOfTrust/keripy HEAD)
          echo HASH=${HASH:0:7} >> $GITHUB_ENV
        # echo $HASH
        # echo "$HASH"

      - name: Show results
        run: |
          echo $HASH
          echo env.HASH