name: Run Shell Commands

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest

    outputs:
      op1: ${{ steps.git_hash_collector.outputs.HASH_2 }}

    steps:
      - name: Run shell commands
        id: git_hash_collector
        run: |
          GIT_HASH=$(git ls-remote https://github.com/WebOfTrust/keripy HEAD)
          echo HASH=${GIT_HASH:0:7} >> $GITHUB_ENV
          echo "::set-output name=HASH_2::${GIT_HASH:0:7}"
  

      - name: Show results
        run: |
          echo $HASH
          echo "${{ env.HASH }}"
          echo "${{ steps.git_hash_collector.outputs.HASH_2 }}"


  job_2:
    runs-on: ubuntu-latest
    needs: job_1

    steps:
      - name: Show results 1
        run: |
          echo ${{ needs.job_1.outputs.op1 }}

